version: '3.5'

services:
  stubby4j-jre11:
    user: root
    image: azagniotov/stubby4j:latest-jre11
    volumes:
      - "./stubby4j-yaml-config:/home/stubby4j/data"
    container_name: stubby4j_jre11
    ports:
      - 8882:8882
      - 8889:8889
      - 7443:7443
    environment:
      YAML_CONFIG: stubs.yaml
      LOCATION: 0.0.0.0
      STUBS_PORT: 8882
      ADMIN_PORT: 8889
      STUBS_TLS_PORT: 7443
      WITH_DEBUG: --debug
      WITH_WATCH: --watch
    networks:
      - bridged

networks:
  bridged:
    driver: bridge